// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://todhdkafikrpupmiftwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZGhka2FmaWtycHVwbWlmdHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTMxNTIsImV4cCI6MjA3MTk2OTE1Mn0.b8oZxTJU8KWrV4m6NsiKaj81lJc_oPeZHCnC5YN0X98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});